version: '3'

services:

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/app/
    links:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ./src:/app/

  pg:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    ports:
      - 4000:5432
    expose:
      - 4000
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    volumes:
      - pg:/data/postgres
volumes:
  pg: